# Generated by Django 4.2.13 on 2024-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_created_date_alter_post_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
        ),
    ]
