# Generated by Django 4.2.13 on 2024-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
